apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: mck-demo
  labels:
    app.kubernetes.io/part-of: mck-demo
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  source: {}

