apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: mck-demo
  namespace: default
  labels:
    app.kubernetes.io/part-of: mck-demo
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: git-ssh
  source:
    git:
      url: ssh://git@github.com/Mpluya/config-mck-demo.git
      ref:
        branch: main

